#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using Quartz;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.Serialization.Formatters.Binary;

public partial class QuartzScheduler : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertQRTZ_BLOB_TRIGGERS(QRTZ_BLOB_TRIGGERS instance);
  partial void UpdateQRTZ_BLOB_TRIGGERS(QRTZ_BLOB_TRIGGERS instance);
  partial void DeleteQRTZ_BLOB_TRIGGERS(QRTZ_BLOB_TRIGGERS instance);
  partial void InsertQRTZ_CALENDARS(QRTZ_CALENDARS instance);
  partial void UpdateQRTZ_CALENDARS(QRTZ_CALENDARS instance);
  partial void DeleteQRTZ_CALENDARS(QRTZ_CALENDARS instance);
  partial void InsertQRTZ_CRON_TRIGGERS(QRTZ_CRON_TRIGGERS instance);
  partial void UpdateQRTZ_CRON_TRIGGERS(QRTZ_CRON_TRIGGERS instance);
  partial void DeleteQRTZ_CRON_TRIGGERS(QRTZ_CRON_TRIGGERS instance);
  partial void InsertQRTZ_FIRED_TRIGGERS(QRTZ_FIRED_TRIGGERS instance);
  partial void UpdateQRTZ_FIRED_TRIGGERS(QRTZ_FIRED_TRIGGERS instance);
  partial void DeleteQRTZ_FIRED_TRIGGERS(QRTZ_FIRED_TRIGGERS instance);
  partial void InsertQRTZ_JOB_DETAILS(QRTZ_JOB_DETAILS instance);
  partial void UpdateQRTZ_JOB_DETAILS(QRTZ_JOB_DETAILS instance);
  partial void DeleteQRTZ_JOB_DETAILS(QRTZ_JOB_DETAILS instance);
  partial void InsertQRTZ_JOB_HISTORY(QRTZ_JOB_HISTORY instance);
  partial void UpdateQRTZ_JOB_HISTORY(QRTZ_JOB_HISTORY instance);
  partial void DeleteQRTZ_JOB_HISTORY(QRTZ_JOB_HISTORY instance);
  partial void InsertQRTZ_LOCKS(QRTZ_LOCKS instance);
  partial void UpdateQRTZ_LOCKS(QRTZ_LOCKS instance);
  partial void DeleteQRTZ_LOCKS(QRTZ_LOCKS instance);
  partial void InsertQRTZ_PAUSED_TRIGGER_GRPS(QRTZ_PAUSED_TRIGGER_GRPS instance);
  partial void UpdateQRTZ_PAUSED_TRIGGER_GRPS(QRTZ_PAUSED_TRIGGER_GRPS instance);
  partial void DeleteQRTZ_PAUSED_TRIGGER_GRPS(QRTZ_PAUSED_TRIGGER_GRPS instance);
  partial void InsertQRTZ_SCHEDULER_STATE(QRTZ_SCHEDULER_STATE instance);
  partial void UpdateQRTZ_SCHEDULER_STATE(QRTZ_SCHEDULER_STATE instance);
  partial void DeleteQRTZ_SCHEDULER_STATE(QRTZ_SCHEDULER_STATE instance);
  partial void InsertQRTZ_SIMPLE_TRIGGERS(QRTZ_SIMPLE_TRIGGERS instance);
  partial void UpdateQRTZ_SIMPLE_TRIGGERS(QRTZ_SIMPLE_TRIGGERS instance);
  partial void DeleteQRTZ_SIMPLE_TRIGGERS(QRTZ_SIMPLE_TRIGGERS instance);
  partial void InsertQRTZ_SIMPROP_TRIGGERS(QRTZ_SIMPROP_TRIGGERS instance);
  partial void UpdateQRTZ_SIMPROP_TRIGGERS(QRTZ_SIMPROP_TRIGGERS instance);
  partial void DeleteQRTZ_SIMPROP_TRIGGERS(QRTZ_SIMPROP_TRIGGERS instance);
  partial void InsertQRTZ_TRIGGERS(QRTZ_TRIGGERS instance);
  partial void UpdateQRTZ_TRIGGERS(QRTZ_TRIGGERS instance);
  partial void DeleteQRTZ_TRIGGERS(QRTZ_TRIGGERS instance);
  #endregion
	
	public QuartzScheduler(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QuartzScheduler(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QuartzScheduler(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QuartzScheduler(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<QRTZ_BLOB_TRIGGERS> QRTZ_BLOB_TRIGGERS
	{
		get
		{
			return this.GetTable<QRTZ_BLOB_TRIGGERS>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_CALENDARS> QRTZ_CALENDARS
	{
		get
		{
			return this.GetTable<QRTZ_CALENDARS>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_CRON_TRIGGERS> QRTZ_CRON_TRIGGERS
	{
		get
		{
			return this.GetTable<QRTZ_CRON_TRIGGERS>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_FIRED_TRIGGERS> QRTZ_FIRED_TRIGGERS
	{
		get
		{
			return this.GetTable<QRTZ_FIRED_TRIGGERS>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_JOB_DETAILS> QRTZ_JOB_DETAILS
	{
		get
		{
			return this.GetTable<QRTZ_JOB_DETAILS>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_JOB_HISTORY> QRTZ_JOB_HISTORY
	{
		get
		{
			return this.GetTable<QRTZ_JOB_HISTORY>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_LOCKS> QRTZ_LOCKS
	{
		get
		{
			return this.GetTable<QRTZ_LOCKS>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_PAUSED_TRIGGER_GRPS> QRTZ_PAUSED_TRIGGER_GRPS
	{
		get
		{
			return this.GetTable<QRTZ_PAUSED_TRIGGER_GRPS>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_SCHEDULER_STATE> QRTZ_SCHEDULER_STATE
	{
		get
		{
			return this.GetTable<QRTZ_SCHEDULER_STATE>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_SIMPLE_TRIGGERS> QRTZ_SIMPLE_TRIGGERS
	{
		get
		{
			return this.GetTable<QRTZ_SIMPLE_TRIGGERS>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_SIMPROP_TRIGGERS> QRTZ_SIMPROP_TRIGGERS
	{
		get
		{
			return this.GetTable<QRTZ_SIMPROP_TRIGGERS>();
		}
	}
	
	public System.Data.Linq.Table<QRTZ_TRIGGERS> QRTZ_TRIGGERS
	{
		get
		{
			return this.GetTable<QRTZ_TRIGGERS>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_BLOB_TRIGGERS")]
public partial class QRTZ_BLOB_TRIGGERS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _TRIGGER_NAME;
	
	private string _TRIGGER_GROUP;
	
	private System.Data.Linq.Binary _BLOB_DATA;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnTRIGGER_NAMEChanging(string value);
    partial void OnTRIGGER_NAMEChanged();
    partial void OnTRIGGER_GROUPChanging(string value);
    partial void OnTRIGGER_GROUPChanged();
    partial void OnBLOB_DATAChanging(System.Data.Linq.Binary value);
    partial void OnBLOB_DATAChanged();
    #endregion
	
	public QRTZ_BLOB_TRIGGERS()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_NAME
	{
		get
		{
			return this._TRIGGER_NAME;
		}
		set
		{
			if ((this._TRIGGER_NAME != value))
			{
				this.OnTRIGGER_NAMEChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_NAME = value;
				this.SendPropertyChanged("TRIGGER_NAME");
				this.OnTRIGGER_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_GROUP
	{
		get
		{
			return this._TRIGGER_GROUP;
		}
		set
		{
			if ((this._TRIGGER_GROUP != value))
			{
				this.OnTRIGGER_GROUPChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_GROUP = value;
				this.SendPropertyChanged("TRIGGER_GROUP");
				this.OnTRIGGER_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOB_DATA", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary BLOB_DATA
	{
		get
		{
			return this._BLOB_DATA;
		}
		set
		{
			if ((this._BLOB_DATA != value))
			{
				this.OnBLOB_DATAChanging(value);
				this.SendPropertyChanging();
				this._BLOB_DATA = value;
				this.SendPropertyChanged("BLOB_DATA");
				this.OnBLOB_DATAChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_CALENDARS")]
public partial class QRTZ_CALENDARS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _CALENDAR_NAME;
	
	private System.Data.Linq.Binary _CALENDAR;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnCALENDAR_NAMEChanging(string value);
    partial void OnCALENDAR_NAMEChanged();
    partial void OnCALENDARChanging(System.Data.Linq.Binary value);
    partial void OnCALENDARChanged();
    #endregion
	
	public QRTZ_CALENDARS()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALENDAR_NAME", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string CALENDAR_NAME
	{
		get
		{
			return this._CALENDAR_NAME;
		}
		set
		{
			if ((this._CALENDAR_NAME != value))
			{
				this.OnCALENDAR_NAMEChanging(value);
				this.SendPropertyChanging();
				this._CALENDAR_NAME = value;
				this.SendPropertyChanged("CALENDAR_NAME");
				this.OnCALENDAR_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALENDAR", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary CALENDAR
	{
		get
		{
			return this._CALENDAR;
		}
		set
		{
			if ((this._CALENDAR != value))
			{
				this.OnCALENDARChanging(value);
				this.SendPropertyChanging();
				this._CALENDAR = value;
				this.SendPropertyChanged("CALENDAR");
				this.OnCALENDARChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_CRON_TRIGGERS")]
public partial class QRTZ_CRON_TRIGGERS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _TRIGGER_NAME;
	
	private string _TRIGGER_GROUP;
	
	private string _CRON_EXPRESSION;
	
	private string _TIME_ZONE_ID;
	
	private EntityRef<QRTZ_TRIGGERS> _QRTZ_TRIGGERS;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnTRIGGER_NAMEChanging(string value);
    partial void OnTRIGGER_NAMEChanged();
    partial void OnTRIGGER_GROUPChanging(string value);
    partial void OnTRIGGER_GROUPChanged();
    partial void OnCRON_EXPRESSIONChanging(string value);
    partial void OnCRON_EXPRESSIONChanged();
    partial void OnTIME_ZONE_IDChanging(string value);
    partial void OnTIME_ZONE_IDChanged();
    #endregion
	
	public QRTZ_CRON_TRIGGERS()
	{
		this._QRTZ_TRIGGERS = default(EntityRef<QRTZ_TRIGGERS>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				if (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_NAME
	{
		get
		{
			return this._TRIGGER_NAME;
		}
		set
		{
			if ((this._TRIGGER_NAME != value))
			{
				if (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTRIGGER_NAMEChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_NAME = value;
				this.SendPropertyChanged("TRIGGER_NAME");
				this.OnTRIGGER_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_GROUP
	{
		get
		{
			return this._TRIGGER_GROUP;
		}
		set
		{
			if ((this._TRIGGER_GROUP != value))
			{
				if (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTRIGGER_GROUPChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_GROUP = value;
				this.SendPropertyChanged("TRIGGER_GROUP");
				this.OnTRIGGER_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRON_EXPRESSION", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
	public string CRON_EXPRESSION
	{
		get
		{
			return this._CRON_EXPRESSION;
		}
		set
		{
			if ((this._CRON_EXPRESSION != value))
			{
				this.OnCRON_EXPRESSIONChanging(value);
				this.SendPropertyChanging();
				this._CRON_EXPRESSION = value;
				this.SendPropertyChanged("CRON_EXPRESSION");
				this.OnCRON_EXPRESSIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_ZONE_ID", DbType="NVarChar(80)")]
	public string TIME_ZONE_ID
	{
		get
		{
			return this._TIME_ZONE_ID;
		}
		set
		{
			if ((this._TIME_ZONE_ID != value))
			{
				this.OnTIME_ZONE_IDChanging(value);
				this.SendPropertyChanging();
				this._TIME_ZONE_ID = value;
				this.SendPropertyChanged("TIME_ZONE_ID");
				this.OnTIME_ZONE_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS", Storage="_QRTZ_TRIGGERS", ThisKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", OtherKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", IsForeignKey=true, DeleteOnNull=true)]
	public QRTZ_TRIGGERS QRTZ_TRIGGERS
	{
		get
		{
			return this._QRTZ_TRIGGERS.Entity;
		}
		set
		{
			QRTZ_TRIGGERS previousValue = this._QRTZ_TRIGGERS.Entity;
			if (((previousValue != value) 
						|| (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._QRTZ_TRIGGERS.Entity = null;
					previousValue.QRTZ_CRON_TRIGGERS = null;
				}
				this._QRTZ_TRIGGERS.Entity = value;
				if ((value != null))
				{
					value.QRTZ_CRON_TRIGGERS = this;
					this._SCHED_NAME = value.SCHED_NAME;
					this._TRIGGER_NAME = value.TRIGGER_NAME;
					this._TRIGGER_GROUP = value.TRIGGER_GROUP;
				}
				else
				{
					this._SCHED_NAME = default(string);
					this._TRIGGER_NAME = default(string);
					this._TRIGGER_GROUP = default(string);
				}
				this.SendPropertyChanged("QRTZ_TRIGGERS");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_FIRED_TRIGGERS")]
public partial class QRTZ_FIRED_TRIGGERS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _ENTRY_ID;
	
	private string _TRIGGER_NAME;
	
	private string _TRIGGER_GROUP;
	
	private string _INSTANCE_NAME;
	
	private long _FIRED_TIME;
	
	private long _SCHED_TIME;
	
	private int _PRIORITY;
	
	private string _STATE;
	
	private string _JOB_NAME;
	
	private string _JOB_GROUP;
	
	private System.Nullable<bool> _IS_NONCONCURRENT;
	
	private System.Nullable<bool> _REQUESTS_RECOVERY;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnENTRY_IDChanging(string value);
    partial void OnENTRY_IDChanged();
    partial void OnTRIGGER_NAMEChanging(string value);
    partial void OnTRIGGER_NAMEChanged();
    partial void OnTRIGGER_GROUPChanging(string value);
    partial void OnTRIGGER_GROUPChanged();
    partial void OnINSTANCE_NAMEChanging(string value);
    partial void OnINSTANCE_NAMEChanged();
    partial void OnFIRED_TIMEChanging(long value);
    partial void OnFIRED_TIMEChanged();
    partial void OnSCHED_TIMEChanging(long value);
    partial void OnSCHED_TIMEChanged();
    partial void OnPRIORITYChanging(int value);
    partial void OnPRIORITYChanged();
    partial void OnSTATEChanging(string value);
    partial void OnSTATEChanged();
    partial void OnJOB_NAMEChanging(string value);
    partial void OnJOB_NAMEChanged();
    partial void OnJOB_GROUPChanging(string value);
    partial void OnJOB_GROUPChanged();
    partial void OnIS_NONCONCURRENTChanging(System.Nullable<bool> value);
    partial void OnIS_NONCONCURRENTChanged();
    partial void OnREQUESTS_RECOVERYChanging(System.Nullable<bool> value);
    partial void OnREQUESTS_RECOVERYChanged();
    #endregion
	
	public QRTZ_FIRED_TRIGGERS()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRY_ID", DbType="NVarChar(140) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ENTRY_ID
	{
		get
		{
			return this._ENTRY_ID;
		}
		set
		{
			if ((this._ENTRY_ID != value))
			{
				this.OnENTRY_IDChanging(value);
				this.SendPropertyChanging();
				this._ENTRY_ID = value;
				this.SendPropertyChanged("ENTRY_ID");
				this.OnENTRY_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string TRIGGER_NAME
	{
		get
		{
			return this._TRIGGER_NAME;
		}
		set
		{
			if ((this._TRIGGER_NAME != value))
			{
				this.OnTRIGGER_NAMEChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_NAME = value;
				this.SendPropertyChanged("TRIGGER_NAME");
				this.OnTRIGGER_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string TRIGGER_GROUP
	{
		get
		{
			return this._TRIGGER_GROUP;
		}
		set
		{
			if ((this._TRIGGER_GROUP != value))
			{
				this.OnTRIGGER_GROUPChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_GROUP = value;
				this.SendPropertyChanged("TRIGGER_GROUP");
				this.OnTRIGGER_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSTANCE_NAME", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string INSTANCE_NAME
	{
		get
		{
			return this._INSTANCE_NAME;
		}
		set
		{
			if ((this._INSTANCE_NAME != value))
			{
				this.OnINSTANCE_NAMEChanging(value);
				this.SendPropertyChanging();
				this._INSTANCE_NAME = value;
				this.SendPropertyChanged("INSTANCE_NAME");
				this.OnINSTANCE_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRED_TIME", DbType="BigInt NOT NULL")]
	public long FIRED_TIME
	{
		get
		{
			return this._FIRED_TIME;
		}
		set
		{
			if ((this._FIRED_TIME != value))
			{
				this.OnFIRED_TIMEChanging(value);
				this.SendPropertyChanging();
				this._FIRED_TIME = value;
				this.SendPropertyChanged("FIRED_TIME");
				this.OnFIRED_TIMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_TIME", DbType="BigInt NOT NULL")]
	public long SCHED_TIME
	{
		get
		{
			return this._SCHED_TIME;
		}
		set
		{
			if ((this._SCHED_TIME != value))
			{
				this.OnSCHED_TIMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_TIME = value;
				this.SendPropertyChanged("SCHED_TIME");
				this.OnSCHED_TIMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORITY", DbType="Int NOT NULL")]
	public int PRIORITY
	{
		get
		{
			return this._PRIORITY;
		}
		set
		{
			if ((this._PRIORITY != value))
			{
				this.OnPRIORITYChanging(value);
				this.SendPropertyChanging();
				this._PRIORITY = value;
				this.SendPropertyChanged("PRIORITY");
				this.OnPRIORITYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
	public string STATE
	{
		get
		{
			return this._STATE;
		}
		set
		{
			if ((this._STATE != value))
			{
				this.OnSTATEChanging(value);
				this.SendPropertyChanging();
				this._STATE = value;
				this.SendPropertyChanged("STATE");
				this.OnSTATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_NAME", DbType="NVarChar(150)")]
	public string JOB_NAME
	{
		get
		{
			return this._JOB_NAME;
		}
		set
		{
			if ((this._JOB_NAME != value))
			{
				this.OnJOB_NAMEChanging(value);
				this.SendPropertyChanging();
				this._JOB_NAME = value;
				this.SendPropertyChanged("JOB_NAME");
				this.OnJOB_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_GROUP", DbType="NVarChar(150)")]
	public string JOB_GROUP
	{
		get
		{
			return this._JOB_GROUP;
		}
		set
		{
			if ((this._JOB_GROUP != value))
			{
				this.OnJOB_GROUPChanging(value);
				this.SendPropertyChanging();
				this._JOB_GROUP = value;
				this.SendPropertyChanged("JOB_GROUP");
				this.OnJOB_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_NONCONCURRENT", DbType="Bit")]
	public System.Nullable<bool> IS_NONCONCURRENT
	{
		get
		{
			return this._IS_NONCONCURRENT;
		}
		set
		{
			if ((this._IS_NONCONCURRENT != value))
			{
				this.OnIS_NONCONCURRENTChanging(value);
				this.SendPropertyChanging();
				this._IS_NONCONCURRENT = value;
				this.SendPropertyChanged("IS_NONCONCURRENT");
				this.OnIS_NONCONCURRENTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUESTS_RECOVERY", DbType="Bit")]
	public System.Nullable<bool> REQUESTS_RECOVERY
	{
		get
		{
			return this._REQUESTS_RECOVERY;
		}
		set
		{
			if ((this._REQUESTS_RECOVERY != value))
			{
				this.OnREQUESTS_RECOVERYChanging(value);
				this.SendPropertyChanging();
				this._REQUESTS_RECOVERY = value;
				this.SendPropertyChanged("REQUESTS_RECOVERY");
				this.OnREQUESTS_RECOVERYChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_JOB_DETAILS")]
public partial class QRTZ_JOB_DETAILS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _JOB_NAME;
	
	private string _JOB_GROUP;
	
	private string _DESCRIPTION;
	
	private string _JOB_CLASS_NAME;
	
	private bool _IS_DURABLE;
	
	private bool _IS_NONCONCURRENT;
	
	private bool _IS_UPDATE_DATA;
	
	private bool _REQUESTS_RECOVERY;
	
	private System.Data.Linq.Binary _JOB_DATA;
	
	private EntitySet<QRTZ_TRIGGERS> _QRTZ_TRIGGERS;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnJOB_NAMEChanging(string value);
    partial void OnJOB_NAMEChanged();
    partial void OnJOB_GROUPChanging(string value);
    partial void OnJOB_GROUPChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnJOB_CLASS_NAMEChanging(string value);
    partial void OnJOB_CLASS_NAMEChanged();
    partial void OnIS_DURABLEChanging(bool value);
    partial void OnIS_DURABLEChanged();
    partial void OnIS_NONCONCURRENTChanging(bool value);
    partial void OnIS_NONCONCURRENTChanged();
    partial void OnIS_UPDATE_DATAChanging(bool value);
    partial void OnIS_UPDATE_DATAChanged();
    partial void OnREQUESTS_RECOVERYChanging(bool value);
    partial void OnREQUESTS_RECOVERYChanged();
    partial void OnJOB_DATAChanging(System.Data.Linq.Binary value);
    partial void OnJOB_DATAChanged();
    #endregion
	
	public QRTZ_JOB_DETAILS()
	{
		this._QRTZ_TRIGGERS = new EntitySet<QRTZ_TRIGGERS>(new Action<QRTZ_TRIGGERS>(this.attach_QRTZ_TRIGGERS), new Action<QRTZ_TRIGGERS>(this.detach_QRTZ_TRIGGERS));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string JOB_NAME
	{
		get
		{
			return this._JOB_NAME;
		}
		set
		{
			if ((this._JOB_NAME != value))
			{
				this.OnJOB_NAMEChanging(value);
				this.SendPropertyChanging();
				this._JOB_NAME = value;
				this.SendPropertyChanged("JOB_NAME");
				this.OnJOB_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string JOB_GROUP
	{
		get
		{
			return this._JOB_GROUP;
		}
		set
		{
			if ((this._JOB_GROUP != value))
			{
				this.OnJOB_GROUPChanging(value);
				this.SendPropertyChanging();
				this._JOB_GROUP = value;
				this.SendPropertyChanged("JOB_GROUP");
				this.OnJOB_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(250)")]
	public string DESCRIPTION
	{
		get
		{
			return this._DESCRIPTION;
		}
		set
		{
			if ((this._DESCRIPTION != value))
			{
				this.OnDESCRIPTIONChanging(value);
				this.SendPropertyChanging();
				this._DESCRIPTION = value;
				this.SendPropertyChanged("DESCRIPTION");
				this.OnDESCRIPTIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_CLASS_NAME", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string JOB_CLASS_NAME
	{
		get
		{
			return this._JOB_CLASS_NAME;
		}
		set
		{
			if ((this._JOB_CLASS_NAME != value))
			{
				this.OnJOB_CLASS_NAMEChanging(value);
				this.SendPropertyChanging();
				this._JOB_CLASS_NAME = value;
				this.SendPropertyChanged("JOB_CLASS_NAME");
				this.OnJOB_CLASS_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_DURABLE", DbType="Bit NOT NULL")]
	public bool IS_DURABLE
	{
		get
		{
			return this._IS_DURABLE;
		}
		set
		{
			if ((this._IS_DURABLE != value))
			{
				this.OnIS_DURABLEChanging(value);
				this.SendPropertyChanging();
				this._IS_DURABLE = value;
				this.SendPropertyChanged("IS_DURABLE");
				this.OnIS_DURABLEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_NONCONCURRENT", DbType="Bit NOT NULL")]
	public bool IS_NONCONCURRENT
	{
		get
		{
			return this._IS_NONCONCURRENT;
		}
		set
		{
			if ((this._IS_NONCONCURRENT != value))
			{
				this.OnIS_NONCONCURRENTChanging(value);
				this.SendPropertyChanging();
				this._IS_NONCONCURRENT = value;
				this.SendPropertyChanged("IS_NONCONCURRENT");
				this.OnIS_NONCONCURRENTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_UPDATE_DATA", DbType="Bit NOT NULL")]
	public bool IS_UPDATE_DATA
	{
		get
		{
			return this._IS_UPDATE_DATA;
		}
		set
		{
			if ((this._IS_UPDATE_DATA != value))
			{
				this.OnIS_UPDATE_DATAChanging(value);
				this.SendPropertyChanging();
				this._IS_UPDATE_DATA = value;
				this.SendPropertyChanged("IS_UPDATE_DATA");
				this.OnIS_UPDATE_DATAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUESTS_RECOVERY", DbType="Bit NOT NULL")]
	public bool REQUESTS_RECOVERY
	{
		get
		{
			return this._REQUESTS_RECOVERY;
		}
		set
		{
			if ((this._REQUESTS_RECOVERY != value))
			{
				this.OnREQUESTS_RECOVERYChanging(value);
				this.SendPropertyChanging();
				this._REQUESTS_RECOVERY = value;
				this.SendPropertyChanged("REQUESTS_RECOVERY");
				this.OnREQUESTS_RECOVERYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_DATA", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary JOB_DATA
	{
		get
		{
			return this._JOB_DATA;
		}
		set
		{
			if ((this._JOB_DATA != value))
			{
				this.OnJOB_DATAChanging(value);
				this.SendPropertyChanging();
				this._JOB_DATA = value;
				this.SendPropertyChanged("JOB_DATA");
				this.OnJOB_DATAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS", Storage="_QRTZ_TRIGGERS", ThisKey="SCHED_NAME,JOB_NAME,JOB_GROUP", OtherKey="SCHED_NAME,JOB_NAME,JOB_GROUP", DeleteRule="NO ACTION")]
	public EntitySet<QRTZ_TRIGGERS> QRTZ_TRIGGERS
	{
		get
		{
			return this._QRTZ_TRIGGERS;
		}
		set
		{
			this._QRTZ_TRIGGERS.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_QRTZ_TRIGGERS(QRTZ_TRIGGERS entity)
	{
		this.SendPropertyChanging();
		entity.QRTZ_JOB_DETAILS = this;
	}
	
	private void detach_QRTZ_TRIGGERS(QRTZ_TRIGGERS entity)
	{
		this.SendPropertyChanging();
		entity.QRTZ_JOB_DETAILS = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_JOB_HISTORY")]
public partial class QRTZ_JOB_HISTORY : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _JOB_HISTORY_ID;
	
	private string _SCHED_NAME;
	
	private string _JOB_NAME;
	
	private string _JOB_GROUP;
	
	private string _STATUSDETAIL;
	
	private System.Nullable<System.DateTime> _STARTDATE;
	
	private System.Nullable<System.DateTime> _ENDDATE;
	
	private System.DateTime _RECORDDATE;
	
	private System.Nullable<bool> _ISEXCEPTION;
	
	private string _LOGFILE;
	
	private string _TRIGGER_NAME;
	
	private string _TRIGGER_GROUP;
	
	private string _JOB_DATA;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJOB_HISTORY_IDChanging(long value);
    partial void OnJOB_HISTORY_IDChanged();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnJOB_NAMEChanging(string value);
    partial void OnJOB_NAMEChanged();
    partial void OnJOB_GROUPChanging(string value);
    partial void OnJOB_GROUPChanged();
    partial void OnSTATUSDETAILChanging(string value);
    partial void OnSTATUSDETAILChanged();
    partial void OnSTARTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTARTDATEChanged();
    partial void OnENDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnENDDATEChanged();
    partial void OnRECORDDATEChanging(System.DateTime value);
    partial void OnRECORDDATEChanged();
    partial void OnISEXCEPTIONChanging(System.Nullable<bool> value);
    partial void OnISEXCEPTIONChanged();
    partial void OnLOGFILEChanging(string value);
    partial void OnLOGFILEChanged();
    partial void OnTRIGGER_NAMEChanging(string value);
    partial void OnTRIGGER_NAMEChanged();
    partial void OnTRIGGER_GROUPChanging(string value);
    partial void OnTRIGGER_GROUPChanged();
    partial void OnJOB_DATAChanging(string value);
    partial void OnJOB_DATAChanged();
    #endregion
	
	public QRTZ_JOB_HISTORY()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_HISTORY_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long JOB_HISTORY_ID
	{
		get
		{
			return this._JOB_HISTORY_ID;
		}
		set
		{
			if ((this._JOB_HISTORY_ID != value))
			{
				this.OnJOB_HISTORY_IDChanging(value);
				this.SendPropertyChanging();
				this._JOB_HISTORY_ID = value;
				this.SendPropertyChanged("JOB_HISTORY_ID");
				this.OnJOB_HISTORY_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string JOB_NAME
	{
		get
		{
			return this._JOB_NAME;
		}
		set
		{
			if ((this._JOB_NAME != value))
			{
				this.OnJOB_NAMEChanging(value);
				this.SendPropertyChanging();
				this._JOB_NAME = value;
				this.SendPropertyChanged("JOB_NAME");
				this.OnJOB_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string JOB_GROUP
	{
		get
		{
			return this._JOB_GROUP;
		}
		set
		{
			if ((this._JOB_GROUP != value))
			{
				this.OnJOB_GROUPChanging(value);
				this.SendPropertyChanging();
				this._JOB_GROUP = value;
				this.SendPropertyChanged("JOB_GROUP");
				this.OnJOB_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSDETAIL", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
	public string STATUSDETAIL
	{
		get
		{
			return this._STATUSDETAIL;
		}
		set
		{
			if ((this._STATUSDETAIL != value))
			{
				this.OnSTATUSDETAILChanging(value);
				this.SendPropertyChanging();
				this._STATUSDETAIL = value;
				this.SendPropertyChanged("STATUSDETAIL");
				this.OnSTATUSDETAILChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTDATE", DbType="DateTime2(7)")]
	public System.Nullable<System.DateTime> STARTDATE
	{
		get
		{
			return this._STARTDATE;
		}
		set
		{
			if ((this._STARTDATE != value))
			{
				this.OnSTARTDATEChanging(value);
				this.SendPropertyChanging();
				this._STARTDATE = value;
				this.SendPropertyChanged("STARTDATE");
				this.OnSTARTDATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="DateTime2(7)")]
	public System.Nullable<System.DateTime> ENDDATE
	{
		get
		{
			return this._ENDDATE;
		}
		set
		{
			if ((this._ENDDATE != value))
			{
				this.OnENDDATEChanging(value);
				this.SendPropertyChanging();
				this._ENDDATE = value;
				this.SendPropertyChanged("ENDDATE");
				this.OnENDDATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDDATE", DbType="DateTime2(7) NOT NULL")]
	public System.DateTime RECORDDATE
	{
		get
		{
			return this._RECORDDATE;
		}
		set
		{
			if ((this._RECORDDATE != value))
			{
				this.OnRECORDDATEChanging(value);
				this.SendPropertyChanging();
				this._RECORDDATE = value;
				this.SendPropertyChanged("RECORDDATE");
				this.OnRECORDDATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISEXCEPTION", DbType="Bit")]
	public System.Nullable<bool> ISEXCEPTION
	{
		get
		{
			return this._ISEXCEPTION;
		}
		set
		{
			if ((this._ISEXCEPTION != value))
			{
				this.OnISEXCEPTIONChanging(value);
				this.SendPropertyChanging();
				this._ISEXCEPTION = value;
				this.SendPropertyChanged("ISEXCEPTION");
				this.OnISEXCEPTIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGFILE", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
	public string LOGFILE
	{
		get
		{
			return this._LOGFILE;
		}
		set
		{
			if ((this._LOGFILE != value))
			{
				this.OnLOGFILEChanging(value);
				this.SendPropertyChanging();
				this._LOGFILE = value;
				this.SendPropertyChanged("LOGFILE");
				this.OnLOGFILEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string TRIGGER_NAME
	{
		get
		{
			return this._TRIGGER_NAME;
		}
		set
		{
			if ((this._TRIGGER_NAME != value))
			{
				this.OnTRIGGER_NAMEChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_NAME = value;
				this.SendPropertyChanged("TRIGGER_NAME");
				this.OnTRIGGER_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string TRIGGER_GROUP
	{
		get
		{
			return this._TRIGGER_GROUP;
		}
		set
		{
			if ((this._TRIGGER_GROUP != value))
			{
				this.OnTRIGGER_GROUPChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_GROUP = value;
				this.SendPropertyChanged("TRIGGER_GROUP");
				this.OnTRIGGER_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_DATA", DbType= "NVarChar(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public string JOB_DATA
	{
		get
		{
			return this._JOB_DATA;
		}
		set
		{
			if ((this._JOB_DATA != value))
			{
				this.OnJOB_DATAChanging(value);
				this.SendPropertyChanging();
				this._JOB_DATA = value;
				this.SendPropertyChanged("JOB_DATA");
				this.OnJOB_DATAChanged();
			}
		}
	}
    public string JobDataToJSON(Binary binary)
    {
        using (MemoryStream ms = new MemoryStream())
        {

            ms.Write(binary.ToArray(), 0, binary.Length);
            ms.Position = 0;
            BinaryFormatter bf = new BinaryFormatter();
            JobDataMap map = bf.Deserialize(ms) as JobDataMap;
            return JsonConvert.SerializeObject(map);
        }

    }

	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_LOCKS")]
public partial class QRTZ_LOCKS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _LOCK_NAME;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnLOCK_NAMEChanging(string value);
    partial void OnLOCK_NAMEChanged();
    #endregion
	
	public QRTZ_LOCKS()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCK_NAME", DbType="NVarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string LOCK_NAME
	{
		get
		{
			return this._LOCK_NAME;
		}
		set
		{
			if ((this._LOCK_NAME != value))
			{
				this.OnLOCK_NAMEChanging(value);
				this.SendPropertyChanging();
				this._LOCK_NAME = value;
				this.SendPropertyChanged("LOCK_NAME");
				this.OnLOCK_NAMEChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_PAUSED_TRIGGER_GRPS")]
public partial class QRTZ_PAUSED_TRIGGER_GRPS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _TRIGGER_GROUP;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnTRIGGER_GROUPChanging(string value);
    partial void OnTRIGGER_GROUPChanged();
    #endregion
	
	public QRTZ_PAUSED_TRIGGER_GRPS()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_GROUP
	{
		get
		{
			return this._TRIGGER_GROUP;
		}
		set
		{
			if ((this._TRIGGER_GROUP != value))
			{
				this.OnTRIGGER_GROUPChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_GROUP = value;
				this.SendPropertyChanged("TRIGGER_GROUP");
				this.OnTRIGGER_GROUPChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_SCHEDULER_STATE")]
public partial class QRTZ_SCHEDULER_STATE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _INSTANCE_NAME;
	
	private long _LAST_CHECKIN_TIME;
	
	private long _CHECKIN_INTERVAL;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnINSTANCE_NAMEChanging(string value);
    partial void OnINSTANCE_NAMEChanged();
    partial void OnLAST_CHECKIN_TIMEChanging(long value);
    partial void OnLAST_CHECKIN_TIMEChanged();
    partial void OnCHECKIN_INTERVALChanging(long value);
    partial void OnCHECKIN_INTERVALChanged();
    #endregion
	
	public QRTZ_SCHEDULER_STATE()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSTANCE_NAME", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string INSTANCE_NAME
	{
		get
		{
			return this._INSTANCE_NAME;
		}
		set
		{
			if ((this._INSTANCE_NAME != value))
			{
				this.OnINSTANCE_NAMEChanging(value);
				this.SendPropertyChanging();
				this._INSTANCE_NAME = value;
				this.SendPropertyChanged("INSTANCE_NAME");
				this.OnINSTANCE_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_CHECKIN_TIME", DbType="BigInt NOT NULL")]
	public long LAST_CHECKIN_TIME
	{
		get
		{
			return this._LAST_CHECKIN_TIME;
		}
		set
		{
			if ((this._LAST_CHECKIN_TIME != value))
			{
				this.OnLAST_CHECKIN_TIMEChanging(value);
				this.SendPropertyChanging();
				this._LAST_CHECKIN_TIME = value;
				this.SendPropertyChanged("LAST_CHECKIN_TIME");
				this.OnLAST_CHECKIN_TIMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECKIN_INTERVAL", DbType="BigInt NOT NULL")]
	public long CHECKIN_INTERVAL
	{
		get
		{
			return this._CHECKIN_INTERVAL;
		}
		set
		{
			if ((this._CHECKIN_INTERVAL != value))
			{
				this.OnCHECKIN_INTERVALChanging(value);
				this.SendPropertyChanging();
				this._CHECKIN_INTERVAL = value;
				this.SendPropertyChanged("CHECKIN_INTERVAL");
				this.OnCHECKIN_INTERVALChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_SIMPLE_TRIGGERS")]
public partial class QRTZ_SIMPLE_TRIGGERS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _TRIGGER_NAME;
	
	private string _TRIGGER_GROUP;
	
	private int _REPEAT_COUNT;
	
	private long _REPEAT_INTERVAL;
	
	private int _TIMES_TRIGGERED;
	
	private EntityRef<QRTZ_TRIGGERS> _QRTZ_TRIGGERS;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnTRIGGER_NAMEChanging(string value);
    partial void OnTRIGGER_NAMEChanged();
    partial void OnTRIGGER_GROUPChanging(string value);
    partial void OnTRIGGER_GROUPChanged();
    partial void OnREPEAT_COUNTChanging(int value);
    partial void OnREPEAT_COUNTChanged();
    partial void OnREPEAT_INTERVALChanging(long value);
    partial void OnREPEAT_INTERVALChanged();
    partial void OnTIMES_TRIGGEREDChanging(int value);
    partial void OnTIMES_TRIGGEREDChanged();
    #endregion
	
	public QRTZ_SIMPLE_TRIGGERS()
	{
		this._QRTZ_TRIGGERS = default(EntityRef<QRTZ_TRIGGERS>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				if (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_NAME
	{
		get
		{
			return this._TRIGGER_NAME;
		}
		set
		{
			if ((this._TRIGGER_NAME != value))
			{
				if (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTRIGGER_NAMEChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_NAME = value;
				this.SendPropertyChanged("TRIGGER_NAME");
				this.OnTRIGGER_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_GROUP
	{
		get
		{
			return this._TRIGGER_GROUP;
		}
		set
		{
			if ((this._TRIGGER_GROUP != value))
			{
				if (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTRIGGER_GROUPChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_GROUP = value;
				this.SendPropertyChanged("TRIGGER_GROUP");
				this.OnTRIGGER_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPEAT_COUNT", DbType="Int NOT NULL")]
	public int REPEAT_COUNT
	{
		get
		{
			return this._REPEAT_COUNT;
		}
		set
		{
			if ((this._REPEAT_COUNT != value))
			{
				this.OnREPEAT_COUNTChanging(value);
				this.SendPropertyChanging();
				this._REPEAT_COUNT = value;
				this.SendPropertyChanged("REPEAT_COUNT");
				this.OnREPEAT_COUNTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPEAT_INTERVAL", DbType="BigInt NOT NULL")]
	public long REPEAT_INTERVAL
	{
		get
		{
			return this._REPEAT_INTERVAL;
		}
		set
		{
			if ((this._REPEAT_INTERVAL != value))
			{
				this.OnREPEAT_INTERVALChanging(value);
				this.SendPropertyChanging();
				this._REPEAT_INTERVAL = value;
				this.SendPropertyChanged("REPEAT_INTERVAL");
				this.OnREPEAT_INTERVALChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMES_TRIGGERED", DbType="Int NOT NULL")]
	public int TIMES_TRIGGERED
	{
		get
		{
			return this._TIMES_TRIGGERED;
		}
		set
		{
			if ((this._TIMES_TRIGGERED != value))
			{
				this.OnTIMES_TRIGGEREDChanging(value);
				this.SendPropertyChanging();
				this._TIMES_TRIGGERED = value;
				this.SendPropertyChanged("TIMES_TRIGGERED");
				this.OnTIMES_TRIGGEREDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS", Storage="_QRTZ_TRIGGERS", ThisKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", OtherKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", IsForeignKey=true, DeleteOnNull=true)]
	public QRTZ_TRIGGERS QRTZ_TRIGGERS
	{
		get
		{
			return this._QRTZ_TRIGGERS.Entity;
		}
		set
		{
			QRTZ_TRIGGERS previousValue = this._QRTZ_TRIGGERS.Entity;
			if (((previousValue != value) 
						|| (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._QRTZ_TRIGGERS.Entity = null;
					previousValue.QRTZ_SIMPLE_TRIGGERS = null;
				}
				this._QRTZ_TRIGGERS.Entity = value;
				if ((value != null))
				{
					value.QRTZ_SIMPLE_TRIGGERS = this;
					this._SCHED_NAME = value.SCHED_NAME;
					this._TRIGGER_NAME = value.TRIGGER_NAME;
					this._TRIGGER_GROUP = value.TRIGGER_GROUP;
				}
				else
				{
					this._SCHED_NAME = default(string);
					this._TRIGGER_NAME = default(string);
					this._TRIGGER_GROUP = default(string);
				}
				this.SendPropertyChanged("QRTZ_TRIGGERS");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_SIMPROP_TRIGGERS")]
public partial class QRTZ_SIMPROP_TRIGGERS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _TRIGGER_NAME;
	
	private string _TRIGGER_GROUP;
	
	private string _STR_PROP_1;
	
	private string _STR_PROP_2;
	
	private string _STR_PROP_3;
	
	private System.Nullable<int> _INT_PROP_1;
	
	private System.Nullable<int> _INT_PROP_2;
	
	private System.Nullable<long> _LONG_PROP_1;
	
	private System.Nullable<long> _LONG_PROP_2;
	
	private System.Nullable<decimal> _DEC_PROP_1;
	
	private System.Nullable<decimal> _DEC_PROP_2;
	
	private System.Nullable<bool> _BOOL_PROP_1;
	
	private System.Nullable<bool> _BOOL_PROP_2;
	
	private string _TIME_ZONE_ID;
	
	private EntityRef<QRTZ_TRIGGERS> _QRTZ_TRIGGERS;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnTRIGGER_NAMEChanging(string value);
    partial void OnTRIGGER_NAMEChanged();
    partial void OnTRIGGER_GROUPChanging(string value);
    partial void OnTRIGGER_GROUPChanged();
    partial void OnSTR_PROP_1Changing(string value);
    partial void OnSTR_PROP_1Changed();
    partial void OnSTR_PROP_2Changing(string value);
    partial void OnSTR_PROP_2Changed();
    partial void OnSTR_PROP_3Changing(string value);
    partial void OnSTR_PROP_3Changed();
    partial void OnINT_PROP_1Changing(System.Nullable<int> value);
    partial void OnINT_PROP_1Changed();
    partial void OnINT_PROP_2Changing(System.Nullable<int> value);
    partial void OnINT_PROP_2Changed();
    partial void OnLONG_PROP_1Changing(System.Nullable<long> value);
    partial void OnLONG_PROP_1Changed();
    partial void OnLONG_PROP_2Changing(System.Nullable<long> value);
    partial void OnLONG_PROP_2Changed();
    partial void OnDEC_PROP_1Changing(System.Nullable<decimal> value);
    partial void OnDEC_PROP_1Changed();
    partial void OnDEC_PROP_2Changing(System.Nullable<decimal> value);
    partial void OnDEC_PROP_2Changed();
    partial void OnBOOL_PROP_1Changing(System.Nullable<bool> value);
    partial void OnBOOL_PROP_1Changed();
    partial void OnBOOL_PROP_2Changing(System.Nullable<bool> value);
    partial void OnBOOL_PROP_2Changed();
    partial void OnTIME_ZONE_IDChanging(string value);
    partial void OnTIME_ZONE_IDChanged();
    #endregion
	
	public QRTZ_SIMPROP_TRIGGERS()
	{
		this._QRTZ_TRIGGERS = default(EntityRef<QRTZ_TRIGGERS>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				if (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_NAME
	{
		get
		{
			return this._TRIGGER_NAME;
		}
		set
		{
			if ((this._TRIGGER_NAME != value))
			{
				if (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTRIGGER_NAMEChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_NAME = value;
				this.SendPropertyChanged("TRIGGER_NAME");
				this.OnTRIGGER_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_GROUP
	{
		get
		{
			return this._TRIGGER_GROUP;
		}
		set
		{
			if ((this._TRIGGER_GROUP != value))
			{
				if (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTRIGGER_GROUPChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_GROUP = value;
				this.SendPropertyChanged("TRIGGER_GROUP");
				this.OnTRIGGER_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_PROP_1", DbType="NVarChar(512)")]
	public string STR_PROP_1
	{
		get
		{
			return this._STR_PROP_1;
		}
		set
		{
			if ((this._STR_PROP_1 != value))
			{
				this.OnSTR_PROP_1Changing(value);
				this.SendPropertyChanging();
				this._STR_PROP_1 = value;
				this.SendPropertyChanged("STR_PROP_1");
				this.OnSTR_PROP_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_PROP_2", DbType="NVarChar(512)")]
	public string STR_PROP_2
	{
		get
		{
			return this._STR_PROP_2;
		}
		set
		{
			if ((this._STR_PROP_2 != value))
			{
				this.OnSTR_PROP_2Changing(value);
				this.SendPropertyChanging();
				this._STR_PROP_2 = value;
				this.SendPropertyChanged("STR_PROP_2");
				this.OnSTR_PROP_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_PROP_3", DbType="NVarChar(512)")]
	public string STR_PROP_3
	{
		get
		{
			return this._STR_PROP_3;
		}
		set
		{
			if ((this._STR_PROP_3 != value))
			{
				this.OnSTR_PROP_3Changing(value);
				this.SendPropertyChanging();
				this._STR_PROP_3 = value;
				this.SendPropertyChanged("STR_PROP_3");
				this.OnSTR_PROP_3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INT_PROP_1", DbType="Int")]
	public System.Nullable<int> INT_PROP_1
	{
		get
		{
			return this._INT_PROP_1;
		}
		set
		{
			if ((this._INT_PROP_1 != value))
			{
				this.OnINT_PROP_1Changing(value);
				this.SendPropertyChanging();
				this._INT_PROP_1 = value;
				this.SendPropertyChanged("INT_PROP_1");
				this.OnINT_PROP_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INT_PROP_2", DbType="Int")]
	public System.Nullable<int> INT_PROP_2
	{
		get
		{
			return this._INT_PROP_2;
		}
		set
		{
			if ((this._INT_PROP_2 != value))
			{
				this.OnINT_PROP_2Changing(value);
				this.SendPropertyChanging();
				this._INT_PROP_2 = value;
				this.SendPropertyChanged("INT_PROP_2");
				this.OnINT_PROP_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONG_PROP_1", DbType="BigInt")]
	public System.Nullable<long> LONG_PROP_1
	{
		get
		{
			return this._LONG_PROP_1;
		}
		set
		{
			if ((this._LONG_PROP_1 != value))
			{
				this.OnLONG_PROP_1Changing(value);
				this.SendPropertyChanging();
				this._LONG_PROP_1 = value;
				this.SendPropertyChanged("LONG_PROP_1");
				this.OnLONG_PROP_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONG_PROP_2", DbType="BigInt")]
	public System.Nullable<long> LONG_PROP_2
	{
		get
		{
			return this._LONG_PROP_2;
		}
		set
		{
			if ((this._LONG_PROP_2 != value))
			{
				this.OnLONG_PROP_2Changing(value);
				this.SendPropertyChanging();
				this._LONG_PROP_2 = value;
				this.SendPropertyChanged("LONG_PROP_2");
				this.OnLONG_PROP_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEC_PROP_1", DbType="Decimal(13,4)")]
	public System.Nullable<decimal> DEC_PROP_1
	{
		get
		{
			return this._DEC_PROP_1;
		}
		set
		{
			if ((this._DEC_PROP_1 != value))
			{
				this.OnDEC_PROP_1Changing(value);
				this.SendPropertyChanging();
				this._DEC_PROP_1 = value;
				this.SendPropertyChanged("DEC_PROP_1");
				this.OnDEC_PROP_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEC_PROP_2", DbType="Decimal(13,4)")]
	public System.Nullable<decimal> DEC_PROP_2
	{
		get
		{
			return this._DEC_PROP_2;
		}
		set
		{
			if ((this._DEC_PROP_2 != value))
			{
				this.OnDEC_PROP_2Changing(value);
				this.SendPropertyChanging();
				this._DEC_PROP_2 = value;
				this.SendPropertyChanged("DEC_PROP_2");
				this.OnDEC_PROP_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOL_PROP_1", DbType="Bit")]
	public System.Nullable<bool> BOOL_PROP_1
	{
		get
		{
			return this._BOOL_PROP_1;
		}
		set
		{
			if ((this._BOOL_PROP_1 != value))
			{
				this.OnBOOL_PROP_1Changing(value);
				this.SendPropertyChanging();
				this._BOOL_PROP_1 = value;
				this.SendPropertyChanged("BOOL_PROP_1");
				this.OnBOOL_PROP_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOL_PROP_2", DbType="Bit")]
	public System.Nullable<bool> BOOL_PROP_2
	{
		get
		{
			return this._BOOL_PROP_2;
		}
		set
		{
			if ((this._BOOL_PROP_2 != value))
			{
				this.OnBOOL_PROP_2Changing(value);
				this.SendPropertyChanging();
				this._BOOL_PROP_2 = value;
				this.SendPropertyChanged("BOOL_PROP_2");
				this.OnBOOL_PROP_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_ZONE_ID", DbType="NVarChar(80)")]
	public string TIME_ZONE_ID
	{
		get
		{
			return this._TIME_ZONE_ID;
		}
		set
		{
			if ((this._TIME_ZONE_ID != value))
			{
				this.OnTIME_ZONE_IDChanging(value);
				this.SendPropertyChanging();
				this._TIME_ZONE_ID = value;
				this.SendPropertyChanged("TIME_ZONE_ID");
				this.OnTIME_ZONE_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS", Storage="_QRTZ_TRIGGERS", ThisKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", OtherKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", IsForeignKey=true, DeleteOnNull=true)]
	public QRTZ_TRIGGERS QRTZ_TRIGGERS
	{
		get
		{
			return this._QRTZ_TRIGGERS.Entity;
		}
		set
		{
			QRTZ_TRIGGERS previousValue = this._QRTZ_TRIGGERS.Entity;
			if (((previousValue != value) 
						|| (this._QRTZ_TRIGGERS.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._QRTZ_TRIGGERS.Entity = null;
					previousValue.QRTZ_SIMPROP_TRIGGERS = null;
				}
				this._QRTZ_TRIGGERS.Entity = value;
				if ((value != null))
				{
					value.QRTZ_SIMPROP_TRIGGERS = this;
					this._SCHED_NAME = value.SCHED_NAME;
					this._TRIGGER_NAME = value.TRIGGER_NAME;
					this._TRIGGER_GROUP = value.TRIGGER_GROUP;
				}
				else
				{
					this._SCHED_NAME = default(string);
					this._TRIGGER_NAME = default(string);
					this._TRIGGER_GROUP = default(string);
				}
				this.SendPropertyChanged("QRTZ_TRIGGERS");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRTZ_TRIGGERS")]
public partial class QRTZ_TRIGGERS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SCHED_NAME;
	
	private string _TRIGGER_NAME;
	
	private string _TRIGGER_GROUP;
	
	private string _JOB_NAME;
	
	private string _JOB_GROUP;
	
	private string _DESCRIPTION;
	
	private System.Nullable<long> _NEXT_FIRE_TIME;
	
	private System.Nullable<long> _PREV_FIRE_TIME;
	
	private System.Nullable<int> _PRIORITY;
	
	private string _TRIGGER_STATE;
	
	private string _TRIGGER_TYPE;
	
	private long _START_TIME;
	
	private System.Nullable<long> _END_TIME;
	
	private string _CALENDAR_NAME;
	
	private System.Nullable<int> _MISFIRE_INSTR;
	
	private System.Data.Linq.Binary _JOB_DATA;
	
	private EntityRef<QRTZ_CRON_TRIGGERS> _QRTZ_CRON_TRIGGERS;
	
	private EntityRef<QRTZ_SIMPLE_TRIGGERS> _QRTZ_SIMPLE_TRIGGERS;
	
	private EntityRef<QRTZ_SIMPROP_TRIGGERS> _QRTZ_SIMPROP_TRIGGERS;
	
	private EntityRef<QRTZ_JOB_DETAILS> _QRTZ_JOB_DETAILS;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCHED_NAMEChanging(string value);
    partial void OnSCHED_NAMEChanged();
    partial void OnTRIGGER_NAMEChanging(string value);
    partial void OnTRIGGER_NAMEChanged();
    partial void OnTRIGGER_GROUPChanging(string value);
    partial void OnTRIGGER_GROUPChanged();
    partial void OnJOB_NAMEChanging(string value);
    partial void OnJOB_NAMEChanged();
    partial void OnJOB_GROUPChanging(string value);
    partial void OnJOB_GROUPChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnNEXT_FIRE_TIMEChanging(System.Nullable<long> value);
    partial void OnNEXT_FIRE_TIMEChanged();
    partial void OnPREV_FIRE_TIMEChanging(System.Nullable<long> value);
    partial void OnPREV_FIRE_TIMEChanged();
    partial void OnPRIORITYChanging(System.Nullable<int> value);
    partial void OnPRIORITYChanged();
    partial void OnTRIGGER_STATEChanging(string value);
    partial void OnTRIGGER_STATEChanged();
    partial void OnTRIGGER_TYPEChanging(string value);
    partial void OnTRIGGER_TYPEChanged();
    partial void OnSTART_TIMEChanging(long value);
    partial void OnSTART_TIMEChanged();
    partial void OnEND_TIMEChanging(System.Nullable<long> value);
    partial void OnEND_TIMEChanged();
    partial void OnCALENDAR_NAMEChanging(string value);
    partial void OnCALENDAR_NAMEChanged();
    partial void OnMISFIRE_INSTRChanging(System.Nullable<int> value);
    partial void OnMISFIRE_INSTRChanged();
    partial void OnJOB_DATAChanging(System.Data.Linq.Binary value);
    partial void OnJOB_DATAChanged();
    #endregion
	
	public QRTZ_TRIGGERS()
	{
		this._QRTZ_CRON_TRIGGERS = default(EntityRef<QRTZ_CRON_TRIGGERS>);
		this._QRTZ_SIMPLE_TRIGGERS = default(EntityRef<QRTZ_SIMPLE_TRIGGERS>);
		this._QRTZ_SIMPROP_TRIGGERS = default(EntityRef<QRTZ_SIMPROP_TRIGGERS>);
		this._QRTZ_JOB_DETAILS = default(EntityRef<QRTZ_JOB_DETAILS>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHED_NAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SCHED_NAME
	{
		get
		{
			return this._SCHED_NAME;
		}
		set
		{
			if ((this._SCHED_NAME != value))
			{
				if (this._QRTZ_JOB_DETAILS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnSCHED_NAMEChanging(value);
				this.SendPropertyChanging();
				this._SCHED_NAME = value;
				this.SendPropertyChanged("SCHED_NAME");
				this.OnSCHED_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_NAME
	{
		get
		{
			return this._TRIGGER_NAME;
		}
		set
		{
			if ((this._TRIGGER_NAME != value))
			{
				this.OnTRIGGER_NAMEChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_NAME = value;
				this.SendPropertyChanged("TRIGGER_NAME");
				this.OnTRIGGER_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string TRIGGER_GROUP
	{
		get
		{
			return this._TRIGGER_GROUP;
		}
		set
		{
			if ((this._TRIGGER_GROUP != value))
			{
				this.OnTRIGGER_GROUPChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_GROUP = value;
				this.SendPropertyChanged("TRIGGER_GROUP");
				this.OnTRIGGER_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string JOB_NAME
	{
		get
		{
			return this._JOB_NAME;
		}
		set
		{
			if ((this._JOB_NAME != value))
			{
				if (this._QRTZ_JOB_DETAILS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnJOB_NAMEChanging(value);
				this.SendPropertyChanging();
				this._JOB_NAME = value;
				this.SendPropertyChanged("JOB_NAME");
				this.OnJOB_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_GROUP", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string JOB_GROUP
	{
		get
		{
			return this._JOB_GROUP;
		}
		set
		{
			if ((this._JOB_GROUP != value))
			{
				if (this._QRTZ_JOB_DETAILS.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnJOB_GROUPChanging(value);
				this.SendPropertyChanging();
				this._JOB_GROUP = value;
				this.SendPropertyChanged("JOB_GROUP");
				this.OnJOB_GROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(250)")]
	public string DESCRIPTION
	{
		get
		{
			return this._DESCRIPTION;
		}
		set
		{
			if ((this._DESCRIPTION != value))
			{
				this.OnDESCRIPTIONChanging(value);
				this.SendPropertyChanging();
				this._DESCRIPTION = value;
				this.SendPropertyChanged("DESCRIPTION");
				this.OnDESCRIPTIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEXT_FIRE_TIME", DbType="BigInt")]
	public System.Nullable<long> NEXT_FIRE_TIME
	{
		get
		{
			return this._NEXT_FIRE_TIME;
		}
		set
		{
			if ((this._NEXT_FIRE_TIME != value))
			{
				this.OnNEXT_FIRE_TIMEChanging(value);
				this.SendPropertyChanging();
				this._NEXT_FIRE_TIME = value;
				this.SendPropertyChanged("NEXT_FIRE_TIME");
				this.OnNEXT_FIRE_TIMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREV_FIRE_TIME", DbType="BigInt")]
	public System.Nullable<long> PREV_FIRE_TIME
	{
		get
		{
			return this._PREV_FIRE_TIME;
		}
		set
		{
			if ((this._PREV_FIRE_TIME != value))
			{
				this.OnPREV_FIRE_TIMEChanging(value);
				this.SendPropertyChanging();
				this._PREV_FIRE_TIME = value;
				this.SendPropertyChanged("PREV_FIRE_TIME");
				this.OnPREV_FIRE_TIMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORITY", DbType="Int")]
	public System.Nullable<int> PRIORITY
	{
		get
		{
			return this._PRIORITY;
		}
		set
		{
			if ((this._PRIORITY != value))
			{
				this.OnPRIORITYChanging(value);
				this.SendPropertyChanging();
				this._PRIORITY = value;
				this.SendPropertyChanged("PRIORITY");
				this.OnPRIORITYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_STATE", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
	public string TRIGGER_STATE
	{
		get
		{
			return this._TRIGGER_STATE;
		}
		set
		{
			if ((this._TRIGGER_STATE != value))
			{
				this.OnTRIGGER_STATEChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_STATE = value;
				this.SendPropertyChanged("TRIGGER_STATE");
				this.OnTRIGGER_STATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGGER_TYPE", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
	public string TRIGGER_TYPE
	{
		get
		{
			return this._TRIGGER_TYPE;
		}
		set
		{
			if ((this._TRIGGER_TYPE != value))
			{
				this.OnTRIGGER_TYPEChanging(value);
				this.SendPropertyChanging();
				this._TRIGGER_TYPE = value;
				this.SendPropertyChanged("TRIGGER_TYPE");
				this.OnTRIGGER_TYPEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_TIME", DbType="BigInt NOT NULL")]
	public long START_TIME
	{
		get
		{
			return this._START_TIME;
		}
		set
		{
			if ((this._START_TIME != value))
			{
				this.OnSTART_TIMEChanging(value);
				this.SendPropertyChanging();
				this._START_TIME = value;
				this.SendPropertyChanged("START_TIME");
				this.OnSTART_TIMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_TIME", DbType="BigInt")]
	public System.Nullable<long> END_TIME
	{
		get
		{
			return this._END_TIME;
		}
		set
		{
			if ((this._END_TIME != value))
			{
				this.OnEND_TIMEChanging(value);
				this.SendPropertyChanging();
				this._END_TIME = value;
				this.SendPropertyChanged("END_TIME");
				this.OnEND_TIMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALENDAR_NAME", DbType="NVarChar(200)")]
	public string CALENDAR_NAME
	{
		get
		{
			return this._CALENDAR_NAME;
		}
		set
		{
			if ((this._CALENDAR_NAME != value))
			{
				this.OnCALENDAR_NAMEChanging(value);
				this.SendPropertyChanging();
				this._CALENDAR_NAME = value;
				this.SendPropertyChanged("CALENDAR_NAME");
				this.OnCALENDAR_NAMEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MISFIRE_INSTR", DbType="Int")]
	public System.Nullable<int> MISFIRE_INSTR
	{
		get
		{
			return this._MISFIRE_INSTR;
		}
		set
		{
			if ((this._MISFIRE_INSTR != value))
			{
				this.OnMISFIRE_INSTRChanging(value);
				this.SendPropertyChanging();
				this._MISFIRE_INSTR = value;
				this.SendPropertyChanged("MISFIRE_INSTR");
				this.OnMISFIRE_INSTRChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_DATA", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary JOB_DATA
	{
		get
		{
			return this._JOB_DATA;
		}
		set
		{
			if ((this._JOB_DATA != value))
			{
				this.OnJOB_DATAChanging(value);
				this.SendPropertyChanging();
				this._JOB_DATA = value;
				this.SendPropertyChanged("JOB_DATA");
				this.OnJOB_DATAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS", Storage="_QRTZ_CRON_TRIGGERS", ThisKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", OtherKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", IsUnique=true, IsForeignKey=false, DeleteRule="CASCADE")]
	public QRTZ_CRON_TRIGGERS QRTZ_CRON_TRIGGERS
	{
		get
		{
			return this._QRTZ_CRON_TRIGGERS.Entity;
		}
		set
		{
			QRTZ_CRON_TRIGGERS previousValue = this._QRTZ_CRON_TRIGGERS.Entity;
			if (((previousValue != value) 
						|| (this._QRTZ_CRON_TRIGGERS.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._QRTZ_CRON_TRIGGERS.Entity = null;
					previousValue.QRTZ_TRIGGERS = null;
				}
				this._QRTZ_CRON_TRIGGERS.Entity = value;
				if ((value != null))
				{
					value.QRTZ_TRIGGERS = this;
				}
				this.SendPropertyChanged("QRTZ_CRON_TRIGGERS");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS", Storage="_QRTZ_SIMPLE_TRIGGERS", ThisKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", OtherKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", IsUnique=true, IsForeignKey=false, DeleteRule="CASCADE")]
	public QRTZ_SIMPLE_TRIGGERS QRTZ_SIMPLE_TRIGGERS
	{
		get
		{
			return this._QRTZ_SIMPLE_TRIGGERS.Entity;
		}
		set
		{
			QRTZ_SIMPLE_TRIGGERS previousValue = this._QRTZ_SIMPLE_TRIGGERS.Entity;
			if (((previousValue != value) 
						|| (this._QRTZ_SIMPLE_TRIGGERS.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._QRTZ_SIMPLE_TRIGGERS.Entity = null;
					previousValue.QRTZ_TRIGGERS = null;
				}
				this._QRTZ_SIMPLE_TRIGGERS.Entity = value;
				if ((value != null))
				{
					value.QRTZ_TRIGGERS = this;
				}
				this.SendPropertyChanged("QRTZ_SIMPLE_TRIGGERS");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS", Storage="_QRTZ_SIMPROP_TRIGGERS", ThisKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", OtherKey="SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP", IsUnique=true, IsForeignKey=false, DeleteRule="CASCADE")]
	public QRTZ_SIMPROP_TRIGGERS QRTZ_SIMPROP_TRIGGERS
	{
		get
		{
			return this._QRTZ_SIMPROP_TRIGGERS.Entity;
		}
		set
		{
			QRTZ_SIMPROP_TRIGGERS previousValue = this._QRTZ_SIMPROP_TRIGGERS.Entity;
			if (((previousValue != value) 
						|| (this._QRTZ_SIMPROP_TRIGGERS.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._QRTZ_SIMPROP_TRIGGERS.Entity = null;
					previousValue.QRTZ_TRIGGERS = null;
				}
				this._QRTZ_SIMPROP_TRIGGERS.Entity = value;
				if ((value != null))
				{
					value.QRTZ_TRIGGERS = this;
				}
				this.SendPropertyChanged("QRTZ_SIMPROP_TRIGGERS");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS", Storage="_QRTZ_JOB_DETAILS", ThisKey="SCHED_NAME,JOB_NAME,JOB_GROUP", OtherKey="SCHED_NAME,JOB_NAME,JOB_GROUP", IsForeignKey=true)]
	public QRTZ_JOB_DETAILS QRTZ_JOB_DETAILS
	{
		get
		{
			return this._QRTZ_JOB_DETAILS.Entity;
		}
		set
		{
			QRTZ_JOB_DETAILS previousValue = this._QRTZ_JOB_DETAILS.Entity;
			if (((previousValue != value) 
						|| (this._QRTZ_JOB_DETAILS.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._QRTZ_JOB_DETAILS.Entity = null;
					previousValue.QRTZ_TRIGGERS.Remove(this);
				}
				this._QRTZ_JOB_DETAILS.Entity = value;
				if ((value != null))
				{
					value.QRTZ_TRIGGERS.Add(this);
					this._SCHED_NAME = value.SCHED_NAME;
					this._JOB_NAME = value.JOB_NAME;
					this._JOB_GROUP = value.JOB_GROUP;
				}
				else
				{
					this._SCHED_NAME = default(string);
					this._JOB_NAME = default(string);
					this._JOB_GROUP = default(string);
				}
				this.SendPropertyChanged("QRTZ_JOB_DETAILS");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
